### ISSUE TITLE
The Service Principal Name (SPN) for the remote computer name and port does not exist.

### ISSUE THREAD

**Issue by cloudmelon** [mspnp/identity-reference-architectures#13]
Tried a few attempts for ad forest architecture getting the same error on Output 005. 

Here's the step that I the error encounter
https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/identity/adds-forest#deploy-the-simulated-on-premises-datacenter

![image](https://user-images.githubusercontent.com/4621560/99668544-cdef2f00-2a65-11eb-950a-e24a57534f33.png)

Please feel free to ping me for further details

**Comment by magrande** [comment]
@cloudmelon Thank you for raising this issue. A fix for this issue is going to go live soon. The fix is a simple update of the xActiveDirectory PS module contained inside the DSC extension zip file (from version 2.16.0.0 to 2.24.0.0). I am closing this issue, please let us know if you still see any other problem.

**Comment by cloudmelon** [comment]
Thanks @magrande for the updates, so I gave another go right after and it worked.
